<?php

declare(strict_types=1);

use ArtisanBuild\Hallway\Channels\Enums\ChannelPermissionTypes;
use ArtisanBuild\Hallway\Channels\Enums\ChannelTypes;
use ArtisanBuild\Hallway\Members\Enums\MemberRoles;
use ArtisanBuild\Hallway\Moderation\Enums\ModerationMemberStates;
use ArtisanBuild\Hallway\Payment\Enums\PaymentStates;

test('read permissions for private free channels', function (
    MemberRoles $role,
    PaymentStates $payment_state,
    ModerationMemberStates $moderation_state,
    bool $in_channel,
    bool $expected,
): void {
    channel_permissions(
        channel_type: ChannelTypes::PrivateFree,
        permission_type: ChannelPermissionTypes::Read,
        role: $role,
        payment_state: $payment_state,
        moderation_state: $moderation_state,
        in_channel: $in_channel,
        expected: $expected,
    );
})->with([
    // Members and pseudo-members not subject to payment and moderation variation
    [MemberRoles::Owner, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::Admin, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::Moderator, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, false, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, true, false],
    // Variation in Payment States
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, false, false],
    // Now test member types as exempt from payment on the moderation status variables
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, true, true],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, true, true],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, true, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, true, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, false, false],
]);

test('write permissions for private free channels', function (
    MemberRoles $role,
    PaymentStates $payment_state,
    ModerationMemberStates $moderation_state,
    bool $in_channel,
    bool $expected,
): void {
    channel_permissions(
        channel_type: ChannelTypes::PrivateFree,
        permission_type: ChannelPermissionTypes::Write,
        role: $role,
        payment_state: $payment_state,
        moderation_state: $moderation_state,
        in_channel: $in_channel,
        expected: $expected,
    );
})->with([
    // Members and pseudo-members not subject to payment and moderation variation
    [MemberRoles::Owner, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::Admin, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::Moderator, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, false, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, true, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, false, false],
    // Variation in Payment States
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, false, false],
    // Now test member types as exempt from payment on the moderation status variables
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, false, false],
]);

test('comment permissions for private free channels', function (
    MemberRoles $role,
    PaymentStates $payment_state,
    ModerationMemberStates $moderation_state,
    bool $in_channel,
    bool $expected,
): void {
    channel_permissions(
        channel_type: ChannelTypes::PrivateFree,
        permission_type: ChannelPermissionTypes::Comment,
        role: $role,
        payment_state: $payment_state,
        moderation_state: $moderation_state,
        in_channel: $in_channel,
        expected: $expected,
    );
})->with([
    // Members and pseudo-members not subject to payment and moderation variation
    [MemberRoles::Owner, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::Admin, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::Moderator, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, true, true],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, false, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, true, false],
    // Variation in Payment States
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, false, false],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, true, true],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, false, false],
    // Now test member types as exempt from payment on the moderation status variables
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, false, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, true, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, false, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, true, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, false, false],
]);
