name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Thank you for your pull request. However, you have submitted this PR on a read-only sub split of `artisan-build/kibble`. Please see https://community.artisan.build/contributing.md for details on how to contribute to this project."
