name: Lint
on: [workflow_call]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Prepare the environment
        run: cp .env.example .env
      - name: Set up Flux
        env:
          FLUX_USERNAME: ${{ secrets.FLUX_USERNAME }}
          FLUX_LICENSE_KEY: ${{ secrets.FLUX_LICENSE_KEY }}
        run: composer config http-basic.composer.fluxui.dev "$FLUX_USERNAME" "$FLUX_LICENSE_KEY"
      - name: Install composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Lint
        run: vendor/bin/pint --test
