name: Stan
on: [workflow_call]

jobs:
  stan:
    strategy:
      matrix:
        operating-system:
          - ubuntu-20.04
        php-version:
          - '8.3'
    name: php ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, zlib, :php-psr
          coverage: none
      - name: Prepare the environment
        run: cp .env.example .env
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Set up Flux
        env:
          FLUX_USERNAME: ${{ secrets.FLUX_USERNAME }}
          FLUX_LICENSE_KEY: ${{ secrets.FLUX_LICENSE_KEY }}
        run: composer config http-basic.composer.fluxui.dev "$FLUX_USERNAME" "$FLUX_LICENSE_KEY"
      - name: Set up GitHub credentials for private packages
        run: composer config --global github-oauth.github.com ${{ secrets.GH_TOKEN }}
      - name: Install composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run stan
        run: vendor/bin/phpstan analyse
